// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIntent struct {
	ID              string             `json:"id"`
	Code            string             `json:"code"`
	Messenger       string             `json:"messenger"`
	Audience        string             `json:"audience"`
	SubjectID       string             `json:"subject_id"`
	State           string             `json:"state"`
	IdentityJson    []byte             `json:"identity_json"`
	MetadataJson    []byte             `json:"metadata_json"`
	RedemptionMode  string             `json:"redemption_mode"`
	MaxRedemptions  int32              `json:"max_redemptions"`
	RedemptionCount int32              `json:"redemption_count"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
}

type CatalogHead struct {
	Singleton  bool               `json:"singleton"`
	SnapshotID string             `json:"snapshot_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CatalogSnapshot struct {
	ID           string             `json:"id"`
	M49ReleaseID int64              `json:"m49_release_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CatalogSnapshotRelease struct {
	SnapshotID string `json:"snapshot_id"`
	DatasetID  string `json:"dataset_id"`
	ReleaseID  int64  `json:"release_id"`
}

type Dataset struct {
	ID             string             `json:"id"`
	WhoIndicatorID string             `json:"who_indicator_id"`
	WhoMeasureCode string             `json:"who_measure_code"`
	Title          string             `json:"title"`
	SourceUrl      string             `json:"source_url"`
	Definition     []byte             `json:"definition"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DatasetRelease struct {
	ID                int64              `json:"id"`
	DatasetID         string             `json:"dataset_id"`
	SourceUrl         string             `json:"source_url"`
	Citation          string             `json:"citation"`
	AccessedAt        pgtype.Timestamptz `json:"accessed_at"`
	RawCsv            []byte             `json:"raw_csv"`
	Sha256            string             `json:"sha256"`
	ResponseMetadata  []byte             `json:"response_metadata"`
	CsvHeaders        []byte             `json:"csv_headers"`
	SchemaFingerprint string             `json:"schema_fingerprint"`
	ParserVersion     string             `json:"parser_version"`
	SourceRowCount    int32              `json:"source_row_count"`
	ImportedRowCount  int32              `json:"imported_row_count"`
	DuplicateRowCount int32              `json:"duplicate_row_count"`
	RejectedRowCount  int32              `json:"rejected_row_count"`
	Diagnostics       []byte             `json:"diagnostics"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ImportJob struct {
	ID            int64              `json:"id"`
	DatasetID     pgtype.Text        `json:"dataset_id"`
	ReleaseID     pgtype.Int8        `json:"release_id"`
	RequestedBy   string             `json:"requested_by"`
	ImportKind    string             `json:"import_kind"`
	State         string             `json:"state"`
	SourceUrl     string             `json:"source_url"`
	DiscoveredUrl pgtype.Text        `json:"discovered_url"`
	StagedRawCsv  []byte             `json:"staged_raw_csv"`
	Preview       []byte             `json:"preview"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type M49Geography struct {
	M49ReleaseID  int64       `json:"m49_release_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	GeographyKind string      `json:"geography_kind"`
	IsLeaf        bool        `json:"is_leaf"`
	IsoAlpha2     pgtype.Text `json:"iso_alpha2"`
	IsoAlpha3     pgtype.Text `json:"iso_alpha3"`
}

type M49Group struct {
	M49ReleaseID int64       `json:"m49_release_id"`
	Code         string      `json:"code"`
	ParentCode   pgtype.Text `json:"parent_code"`
	Name         string      `json:"name"`
	GroupKind    string      `json:"group_kind"`
	IsCustom     bool        `json:"is_custom"`
}

type M49GroupMember struct {
	M49ReleaseID  int64  `json:"m49_release_id"`
	GroupCode     string `json:"group_code"`
	GeographyCode string `json:"geography_code"`
}

type M49ReferenceRelease struct {
	ID                    int64              `json:"id"`
	ClassificationVersion string             `json:"classification_version"`
	SourceUrl             string             `json:"source_url"`
	AccessedAt            pgtype.Timestamptz `json:"accessed_at"`
	RawPayload            []byte             `json:"raw_payload"`
	Sha256                string             `json:"sha256"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Measure struct {
	DatasetID   string `json:"dataset_id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Observation struct {
	ID                int64              `json:"id"`
	DatasetID         string             `json:"dataset_id"`
	ReleaseID         int64              `json:"release_id"`
	SeriesID          int64              `json:"series_id"`
	SourceGeographyID int64              `json:"source_geography_id"`
	Year              int16              `json:"year"`
	RawValue          string             `json:"raw_value"`
	DisplayValue      string             `json:"display_value"`
	NumericValue      pgtype.Numeric     `json:"numeric_value"`
	LowerBound        pgtype.Numeric     `json:"lower_bound"`
	UpperBound        pgtype.Numeric     `json:"upper_bound"`
	ValueStatus       string             `json:"value_status"`
	PublishState      string             `json:"publish_state"`
	SourceRowKey      string             `json:"source_row_key"`
	CanonicalM49Code  pgtype.Text        `json:"canonical_m49_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Series struct {
	ID             int64              `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	MeasureCode    string             `json:"measure_code"`
	Label          string             `json:"label"`
	Dimensions     []byte             `json:"dimensions"`
	DimensionsHash string             `json:"dimensions_hash"`
	Unit           string             `json:"unit"`
	Statistic      string             `json:"statistic"`
	ValueKind      string             `json:"value_kind"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SourceGeography struct {
	ID               int64              `json:"id"`
	SourceSystem     string             `json:"source_system"`
	SourceCode       string             `json:"source_code"`
	Name             string             `json:"name"`
	GeographyKind    string             `json:"geography_kind"`
	CanonicalM49Code pgtype.Text        `json:"canonical_m49_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type WebSession struct {
	SessionID string             `json:"session_id"`
	SubjectID string             `json:"subject_id"`
	TokenHash []byte             `json:"token_hash"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
