// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CalculateAssociation(ctx context.Context, arg CalculateAssociationParams) (CalculateAssociationRow, error)
	ConsumeAuthIntent(ctx context.Context, arg ConsumeAuthIntentParams) (AuthIntent, error)
	CountObservationsForSeries(ctx context.Context, arg CountObservationsForSeriesParams) (int64, error)
	DeleteExpiredAuthIntents(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	DeleteWebSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error)
	GetAuthIntentByMessengerCode(ctx context.Context, arg GetAuthIntentByMessengerCodeParams) (AuthIntent, error)
	GetCatalogHead(ctx context.Context) (CatalogSnapshot, error)
	GetM49ReferenceRelease(ctx context.Context, id int64) (M49ReferenceRelease, error)
	GetWebSessionByTokenHash(ctx context.Context, tokenHash []byte) (WebSession, error)
	InsertAuthIntent(ctx context.Context, arg InsertAuthIntentParams) (AuthIntent, error)
	InsertCatalogSnapshot(ctx context.Context, arg InsertCatalogSnapshotParams) (CatalogSnapshot, error)
	InsertCatalogSnapshotRelease(ctx context.Context, arg InsertCatalogSnapshotReleaseParams) error
	InsertDataset(ctx context.Context, arg InsertDatasetParams) (Dataset, error)
	InsertDatasetRelease(ctx context.Context, arg InsertDatasetReleaseParams) (DatasetRelease, error)
	InsertImportJob(ctx context.Context, arg InsertImportJobParams) (ImportJob, error)
	InsertM49Geography(ctx context.Context, arg InsertM49GeographyParams) (M49Geography, error)
	InsertM49Group(ctx context.Context, arg InsertM49GroupParams) (M49Group, error)
	InsertM49GroupMember(ctx context.Context, arg InsertM49GroupMemberParams) error
	InsertM49ReferenceRelease(ctx context.Context, arg InsertM49ReferenceReleaseParams) (M49ReferenceRelease, error)
	InsertMeasure(ctx context.Context, arg InsertMeasureParams) (Measure, error)
	InsertObservation(ctx context.Context, arg InsertObservationParams) (Observation, error)
	InsertSeries(ctx context.Context, arg InsertSeriesParams) (Series, error)
	InsertSourceGeography(ctx context.Context, arg InsertSourceGeographyParams) (InsertSourceGeographyRow, error)
	InsertWebSession(ctx context.Context, arg InsertWebSessionParams) (WebSession, error)
	ListAssociationPoints(ctx context.Context, arg ListAssociationPointsParams) ([]ListAssociationPointsRow, error)
	ListCatalogDatasets(ctx context.Context, snapshotID string) ([]ListCatalogDatasetsRow, error)
	ListCatalogSnapshotReleases(ctx context.Context, snapshotID string) ([]ListCatalogSnapshotReleasesRow, error)
	ListDatasetsWithRelease(ctx context.Context) ([]string, error)
	ListGroupsForM49Release(ctx context.Context, m49ReleaseID int64) ([]ListGroupsForM49ReleaseRow, error)
	ListObservationsForSeries(ctx context.Context, arg ListObservationsForSeriesParams) ([]Observation, error)
	ListReleaseDatasetPairsByIDs(ctx context.Context, dollar_1 []int64) ([]ListReleaseDatasetPairsByIDsRow, error)
	ListSeriesYearsForSnapshot(ctx context.Context, arg ListSeriesYearsForSnapshotParams) ([]int16, error)
	SearchSourceGeographies(ctx context.Context, arg SearchSourceGeographiesParams) ([]SourceGeography, error)
	SetCatalogHead(ctx context.Context, snapshotID string) error
	UpdateImportJob(ctx context.Context, arg UpdateImportJobParams) (ImportJob, error)
}

var _ Querier = (*Queries)(nil)
