// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const calculateAssociation = `-- name: CalculateAssociation :one
SELECT count(*)::bigint AS paired_n,
       coalesce(
           corr(x.numeric_value::double precision, y.numeric_value::double precision),
           'NaN'::double precision
       )::text AS pearson_r
FROM catalog_snapshot_release sx
JOIN observation x ON x.release_id = sx.release_id
JOIN catalog_snapshot_release sy ON sy.snapshot_id = sx.snapshot_id
JOIN observation y ON y.release_id = sy.release_id
WHERE sx.snapshot_id = $1
  AND x.series_id = $2
  AND x.year = $3
  AND y.series_id = $4
  AND y.year = $5
  AND x.value_status = 'numeric'
  AND y.value_status = 'numeric'
  AND x.publish_state = 'PUBLISHED'
  AND y.publish_state = 'PUBLISHED'
  AND x.canonical_m49_code IS NOT NULL
  AND x.canonical_m49_code = y.canonical_m49_code
  AND (coalesce(cardinality($6::text[]), 0) = 0 OR x.canonical_m49_code = ANY($6::text[]))
`

type CalculateAssociationParams struct {
	SnapshotID string   `json:"snapshot_id"`
	SeriesID   int64    `json:"series_id"`
	Year       int16    `json:"year"`
	SeriesID_2 int64    `json:"series_id_2"`
	Year_2     int16    `json:"year_2"`
	Column6    []string `json:"column_6"`
}

type CalculateAssociationRow struct {
	PairedN  int64  `json:"paired_n"`
	PearsonR string `json:"pearson_r"`
}

func (q *Queries) CalculateAssociation(ctx context.Context, arg CalculateAssociationParams) (CalculateAssociationRow, error) {
	row := q.db.QueryRow(ctx, calculateAssociation,
		arg.SnapshotID,
		arg.SeriesID,
		arg.Year,
		arg.SeriesID_2,
		arg.Year_2,
		arg.Column6,
	)
	var i CalculateAssociationRow
	err := row.Scan(&i.PairedN, &i.PearsonR)
	return i, err
}

const consumeAuthIntent = `-- name: ConsumeAuthIntent :one
UPDATE auth_intents
SET redemption_count = $2, consumed_at = $3, state = $4
WHERE id = $1 AND redemption_count = $5 AND state = 'active'
RETURNING id, code, messenger, audience, subject_id, state, identity_json, metadata_json, redemption_mode, max_redemptions, redemption_count, expires_at, created_at, consumed_at
`

type ConsumeAuthIntentParams struct {
	ID                string             `json:"id"`
	RedemptionCount   int32              `json:"redemption_count"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	State             string             `json:"state"`
	RedemptionCount_2 int32              `json:"redemption_count_2"`
}

func (q *Queries) ConsumeAuthIntent(ctx context.Context, arg ConsumeAuthIntentParams) (AuthIntent, error) {
	row := q.db.QueryRow(ctx, consumeAuthIntent,
		arg.ID,
		arg.RedemptionCount,
		arg.ConsumedAt,
		arg.State,
		arg.RedemptionCount_2,
	)
	var i AuthIntent
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Messenger,
		&i.Audience,
		&i.SubjectID,
		&i.State,
		&i.IdentityJson,
		&i.MetadataJson,
		&i.RedemptionMode,
		&i.MaxRedemptions,
		&i.RedemptionCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const countObservationsForSeries = `-- name: CountObservationsForSeries :one
SELECT count(*)
FROM catalog_snapshot_release csr
JOIN observation o ON o.release_id = csr.release_id
WHERE csr.snapshot_id = $1
  AND o.series_id = $2
  AND o.year = ANY($3::smallint[])
`

type CountObservationsForSeriesParams struct {
	SnapshotID string  `json:"snapshot_id"`
	SeriesID   int64   `json:"series_id"`
	Column3    []int16 `json:"column_3"`
}

func (q *Queries) CountObservationsForSeries(ctx context.Context, arg CountObservationsForSeriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countObservationsForSeries, arg.SnapshotID, arg.SeriesID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredAuthIntents = `-- name: DeleteExpiredAuthIntents :execrows
DELETE FROM auth_intents
WHERE expires_at IS NOT NULL AND expires_at < $1
`

func (q *Queries) DeleteExpiredAuthIntents(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthIntents, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionByTokenHash = `-- name: DeleteWebSessionByTokenHash :execrows
DELETE FROM web_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteWebSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthIntentByMessengerCode = `-- name: GetAuthIntentByMessengerCode :one
SELECT id, code, messenger, audience, subject_id, state, identity_json, metadata_json, redemption_mode, max_redemptions, redemption_count, expires_at, created_at, consumed_at
FROM auth_intents
WHERE messenger = $1 AND code = $2
`

type GetAuthIntentByMessengerCodeParams struct {
	Messenger string `json:"messenger"`
	Code      string `json:"code"`
}

func (q *Queries) GetAuthIntentByMessengerCode(ctx context.Context, arg GetAuthIntentByMessengerCodeParams) (AuthIntent, error) {
	row := q.db.QueryRow(ctx, getAuthIntentByMessengerCode, arg.Messenger, arg.Code)
	var i AuthIntent
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Messenger,
		&i.Audience,
		&i.SubjectID,
		&i.State,
		&i.IdentityJson,
		&i.MetadataJson,
		&i.RedemptionMode,
		&i.MaxRedemptions,
		&i.RedemptionCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getCatalogHead = `-- name: GetCatalogHead :one
SELECT s.id, s.m49_release_id, s.created_at
FROM catalog_head h
JOIN catalog_snapshot s ON s.id = h.snapshot_id
WHERE h.singleton
`

func (q *Queries) GetCatalogHead(ctx context.Context) (CatalogSnapshot, error) {
	row := q.db.QueryRow(ctx, getCatalogHead)
	var i CatalogSnapshot
	err := row.Scan(&i.ID, &i.M49ReleaseID, &i.CreatedAt)
	return i, err
}

const getM49ReferenceRelease = `-- name: GetM49ReferenceRelease :one
SELECT id, classification_version, source_url, accessed_at, raw_payload, sha256, created_at FROM m49_reference_release WHERE id = $1
`

func (q *Queries) GetM49ReferenceRelease(ctx context.Context, id int64) (M49ReferenceRelease, error) {
	row := q.db.QueryRow(ctx, getM49ReferenceRelease, id)
	var i M49ReferenceRelease
	err := row.Scan(
		&i.ID,
		&i.ClassificationVersion,
		&i.SourceUrl,
		&i.AccessedAt,
		&i.RawPayload,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getWebSessionByTokenHash = `-- name: GetWebSessionByTokenHash :one
SELECT session_id, subject_id, token_hash, issued_at, expires_at FROM web_sessions WHERE token_hash = $1
`

func (q *Queries) GetWebSessionByTokenHash(ctx context.Context, tokenHash []byte) (WebSession, error) {
	row := q.db.QueryRow(ctx, getWebSessionByTokenHash, tokenHash)
	var i WebSession
	err := row.Scan(
		&i.SessionID,
		&i.SubjectID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAuthIntent = `-- name: InsertAuthIntent :one
INSERT INTO auth_intents (
    id, code, messenger, audience, subject_id, state, identity_json, metadata_json,
    redemption_mode, max_redemptions, redemption_count, expires_at, created_at, consumed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, code, messenger, audience, subject_id, state, identity_json, metadata_json, redemption_mode, max_redemptions, redemption_count, expires_at, created_at, consumed_at
`

type InsertAuthIntentParams struct {
	ID              string             `json:"id"`
	Code            string             `json:"code"`
	Messenger       string             `json:"messenger"`
	Audience        string             `json:"audience"`
	SubjectID       string             `json:"subject_id"`
	State           string             `json:"state"`
	IdentityJson    []byte             `json:"identity_json"`
	MetadataJson    []byte             `json:"metadata_json"`
	RedemptionMode  string             `json:"redemption_mode"`
	MaxRedemptions  int32              `json:"max_redemptions"`
	RedemptionCount int32              `json:"redemption_count"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
}

func (q *Queries) InsertAuthIntent(ctx context.Context, arg InsertAuthIntentParams) (AuthIntent, error) {
	row := q.db.QueryRow(ctx, insertAuthIntent,
		arg.ID,
		arg.Code,
		arg.Messenger,
		arg.Audience,
		arg.SubjectID,
		arg.State,
		arg.IdentityJson,
		arg.MetadataJson,
		arg.RedemptionMode,
		arg.MaxRedemptions,
		arg.RedemptionCount,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.ConsumedAt,
	)
	var i AuthIntent
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Messenger,
		&i.Audience,
		&i.SubjectID,
		&i.State,
		&i.IdentityJson,
		&i.MetadataJson,
		&i.RedemptionMode,
		&i.MaxRedemptions,
		&i.RedemptionCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertCatalogSnapshot = `-- name: InsertCatalogSnapshot :one
INSERT INTO catalog_snapshot (id, m49_release_id)
VALUES ($1, $2)
RETURNING id, m49_release_id, created_at
`

type InsertCatalogSnapshotParams struct {
	ID           string `json:"id"`
	M49ReleaseID int64  `json:"m49_release_id"`
}

func (q *Queries) InsertCatalogSnapshot(ctx context.Context, arg InsertCatalogSnapshotParams) (CatalogSnapshot, error) {
	row := q.db.QueryRow(ctx, insertCatalogSnapshot, arg.ID, arg.M49ReleaseID)
	var i CatalogSnapshot
	err := row.Scan(&i.ID, &i.M49ReleaseID, &i.CreatedAt)
	return i, err
}

const insertCatalogSnapshotRelease = `-- name: InsertCatalogSnapshotRelease :exec
INSERT INTO catalog_snapshot_release (snapshot_id, dataset_id, release_id)
VALUES ($1, $2, $3)
`

type InsertCatalogSnapshotReleaseParams struct {
	SnapshotID string `json:"snapshot_id"`
	DatasetID  string `json:"dataset_id"`
	ReleaseID  int64  `json:"release_id"`
}

func (q *Queries) InsertCatalogSnapshotRelease(ctx context.Context, arg InsertCatalogSnapshotReleaseParams) error {
	_, err := q.db.Exec(ctx, insertCatalogSnapshotRelease, arg.SnapshotID, arg.DatasetID, arg.ReleaseID)
	return err
}

const insertDataset = `-- name: InsertDataset :one
INSERT INTO dataset (id, who_indicator_id, who_measure_code, title, source_url, definition)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
RETURNING id, who_indicator_id, who_measure_code, title, source_url, definition, created_at
`

type InsertDatasetParams struct {
	ID             string `json:"id"`
	WhoIndicatorID string `json:"who_indicator_id"`
	WhoMeasureCode string `json:"who_measure_code"`
	Title          string `json:"title"`
	SourceUrl      string `json:"source_url"`
	Definition     []byte `json:"definition"`
}

func (q *Queries) InsertDataset(ctx context.Context, arg InsertDatasetParams) (Dataset, error) {
	row := q.db.QueryRow(ctx, insertDataset,
		arg.ID,
		arg.WhoIndicatorID,
		arg.WhoMeasureCode,
		arg.Title,
		arg.SourceUrl,
		arg.Definition,
	)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.WhoIndicatorID,
		&i.WhoMeasureCode,
		&i.Title,
		&i.SourceUrl,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const insertDatasetRelease = `-- name: InsertDatasetRelease :one
INSERT INTO dataset_release (
    dataset_id, source_url, citation, accessed_at, raw_csv, sha256, response_metadata, csv_headers,
    schema_fingerprint, parser_version, source_row_count, imported_row_count,
    duplicate_row_count, rejected_row_count, diagnostics
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, dataset_id, source_url, citation, accessed_at, raw_csv, sha256, response_metadata, csv_headers, schema_fingerprint, parser_version, source_row_count, imported_row_count, duplicate_row_count, rejected_row_count, diagnostics, created_at
`

type InsertDatasetReleaseParams struct {
	DatasetID         string             `json:"dataset_id"`
	SourceUrl         string             `json:"source_url"`
	Citation          string             `json:"citation"`
	AccessedAt        pgtype.Timestamptz `json:"accessed_at"`
	RawCsv            []byte             `json:"raw_csv"`
	Sha256            string             `json:"sha256"`
	ResponseMetadata  []byte             `json:"response_metadata"`
	CsvHeaders        []byte             `json:"csv_headers"`
	SchemaFingerprint string             `json:"schema_fingerprint"`
	ParserVersion     string             `json:"parser_version"`
	SourceRowCount    int32              `json:"source_row_count"`
	ImportedRowCount  int32              `json:"imported_row_count"`
	DuplicateRowCount int32              `json:"duplicate_row_count"`
	RejectedRowCount  int32              `json:"rejected_row_count"`
	Diagnostics       []byte             `json:"diagnostics"`
}

func (q *Queries) InsertDatasetRelease(ctx context.Context, arg InsertDatasetReleaseParams) (DatasetRelease, error) {
	row := q.db.QueryRow(ctx, insertDatasetRelease,
		arg.DatasetID,
		arg.SourceUrl,
		arg.Citation,
		arg.AccessedAt,
		arg.RawCsv,
		arg.Sha256,
		arg.ResponseMetadata,
		arg.CsvHeaders,
		arg.SchemaFingerprint,
		arg.ParserVersion,
		arg.SourceRowCount,
		arg.ImportedRowCount,
		arg.DuplicateRowCount,
		arg.RejectedRowCount,
		arg.Diagnostics,
	)
	var i DatasetRelease
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.SourceUrl,
		&i.Citation,
		&i.AccessedAt,
		&i.RawCsv,
		&i.Sha256,
		&i.ResponseMetadata,
		&i.CsvHeaders,
		&i.SchemaFingerprint,
		&i.ParserVersion,
		&i.SourceRowCount,
		&i.ImportedRowCount,
		&i.DuplicateRowCount,
		&i.RejectedRowCount,
		&i.Diagnostics,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportJob = `-- name: InsertImportJob :one
INSERT INTO import_job (dataset_id, requested_by, import_kind, state, source_url, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, dataset_id, release_id, requested_by, import_kind, state, source_url, discovered_url, staged_raw_csv, preview, error_message, expires_at, created_at, started_at, finished_at
`

type InsertImportJobParams struct {
	DatasetID   pgtype.Text        `json:"dataset_id"`
	RequestedBy string             `json:"requested_by"`
	ImportKind  string             `json:"import_kind"`
	State       string             `json:"state"`
	SourceUrl   string             `json:"source_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertImportJob(ctx context.Context, arg InsertImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, insertImportJob,
		arg.DatasetID,
		arg.RequestedBy,
		arg.ImportKind,
		arg.State,
		arg.SourceUrl,
		arg.ExpiresAt,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ReleaseID,
		&i.RequestedBy,
		&i.ImportKind,
		&i.State,
		&i.SourceUrl,
		&i.DiscoveredUrl,
		&i.StagedRawCsv,
		&i.Preview,
		&i.ErrorMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertM49Geography = `-- name: InsertM49Geography :one
INSERT INTO m49_geography (m49_release_id, code, name, geography_kind, is_leaf, iso_alpha2, iso_alpha3)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING m49_release_id, code, name, geography_kind, is_leaf, iso_alpha2, iso_alpha3
`

type InsertM49GeographyParams struct {
	M49ReleaseID  int64       `json:"m49_release_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	GeographyKind string      `json:"geography_kind"`
	IsLeaf        bool        `json:"is_leaf"`
	IsoAlpha2     pgtype.Text `json:"iso_alpha2"`
	IsoAlpha3     pgtype.Text `json:"iso_alpha3"`
}

func (q *Queries) InsertM49Geography(ctx context.Context, arg InsertM49GeographyParams) (M49Geography, error) {
	row := q.db.QueryRow(ctx, insertM49Geography,
		arg.M49ReleaseID,
		arg.Code,
		arg.Name,
		arg.GeographyKind,
		arg.IsLeaf,
		arg.IsoAlpha2,
		arg.IsoAlpha3,
	)
	var i M49Geography
	err := row.Scan(
		&i.M49ReleaseID,
		&i.Code,
		&i.Name,
		&i.GeographyKind,
		&i.IsLeaf,
		&i.IsoAlpha2,
		&i.IsoAlpha3,
	)
	return i, err
}

const insertM49Group = `-- name: InsertM49Group :one
INSERT INTO m49_group (m49_release_id, code, parent_code, name, group_kind, is_custom)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING m49_release_id, code, parent_code, name, group_kind, is_custom
`

type InsertM49GroupParams struct {
	M49ReleaseID int64       `json:"m49_release_id"`
	Code         string      `json:"code"`
	ParentCode   pgtype.Text `json:"parent_code"`
	Name         string      `json:"name"`
	GroupKind    string      `json:"group_kind"`
	IsCustom     bool        `json:"is_custom"`
}

func (q *Queries) InsertM49Group(ctx context.Context, arg InsertM49GroupParams) (M49Group, error) {
	row := q.db.QueryRow(ctx, insertM49Group,
		arg.M49ReleaseID,
		arg.Code,
		arg.ParentCode,
		arg.Name,
		arg.GroupKind,
		arg.IsCustom,
	)
	var i M49Group
	err := row.Scan(
		&i.M49ReleaseID,
		&i.Code,
		&i.ParentCode,
		&i.Name,
		&i.GroupKind,
		&i.IsCustom,
	)
	return i, err
}

const insertM49GroupMember = `-- name: InsertM49GroupMember :exec
INSERT INTO m49_group_member (m49_release_id, group_code, geography_code)
VALUES ($1, $2, $3)
`

type InsertM49GroupMemberParams struct {
	M49ReleaseID  int64  `json:"m49_release_id"`
	GroupCode     string `json:"group_code"`
	GeographyCode string `json:"geography_code"`
}

func (q *Queries) InsertM49GroupMember(ctx context.Context, arg InsertM49GroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertM49GroupMember, arg.M49ReleaseID, arg.GroupCode, arg.GeographyCode)
	return err
}

const insertM49ReferenceRelease = `-- name: InsertM49ReferenceRelease :one
INSERT INTO m49_reference_release (classification_version, source_url, accessed_at, raw_payload, sha256)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, classification_version, source_url, accessed_at, raw_payload, sha256, created_at
`

type InsertM49ReferenceReleaseParams struct {
	ClassificationVersion string             `json:"classification_version"`
	SourceUrl             string             `json:"source_url"`
	AccessedAt            pgtype.Timestamptz `json:"accessed_at"`
	RawPayload            []byte             `json:"raw_payload"`
	Sha256                string             `json:"sha256"`
}

func (q *Queries) InsertM49ReferenceRelease(ctx context.Context, arg InsertM49ReferenceReleaseParams) (M49ReferenceRelease, error) {
	row := q.db.QueryRow(ctx, insertM49ReferenceRelease,
		arg.ClassificationVersion,
		arg.SourceUrl,
		arg.AccessedAt,
		arg.RawPayload,
		arg.Sha256,
	)
	var i M49ReferenceRelease
	err := row.Scan(
		&i.ID,
		&i.ClassificationVersion,
		&i.SourceUrl,
		&i.AccessedAt,
		&i.RawPayload,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const insertMeasure = `-- name: InsertMeasure :one
INSERT INTO measure (dataset_id, code, title, description)
VALUES ($1, $2, $3, $4)
RETURNING dataset_id, code, title, description
`

type InsertMeasureParams struct {
	DatasetID   string `json:"dataset_id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) InsertMeasure(ctx context.Context, arg InsertMeasureParams) (Measure, error) {
	row := q.db.QueryRow(ctx, insertMeasure,
		arg.DatasetID,
		arg.Code,
		arg.Title,
		arg.Description,
	)
	var i Measure
	err := row.Scan(
		&i.DatasetID,
		&i.Code,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :one
INSERT INTO observation (
    dataset_id, release_id, series_id, source_geography_id, year, raw_value,
    display_value, numeric_value, lower_bound, upper_bound, value_status,
    publish_state, source_row_key, canonical_m49_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, dataset_id, release_id, series_id, source_geography_id, year, raw_value, display_value, numeric_value, lower_bound, upper_bound, value_status, publish_state, source_row_key, canonical_m49_code, created_at
`

type InsertObservationParams struct {
	DatasetID         string         `json:"dataset_id"`
	ReleaseID         int64          `json:"release_id"`
	SeriesID          int64          `json:"series_id"`
	SourceGeographyID int64          `json:"source_geography_id"`
	Year              int16          `json:"year"`
	RawValue          string         `json:"raw_value"`
	DisplayValue      string         `json:"display_value"`
	NumericValue      pgtype.Numeric `json:"numeric_value"`
	LowerBound        pgtype.Numeric `json:"lower_bound"`
	UpperBound        pgtype.Numeric `json:"upper_bound"`
	ValueStatus       string         `json:"value_status"`
	PublishState      string         `json:"publish_state"`
	SourceRowKey      string         `json:"source_row_key"`
	CanonicalM49Code  pgtype.Text    `json:"canonical_m49_code"`
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, insertObservation,
		arg.DatasetID,
		arg.ReleaseID,
		arg.SeriesID,
		arg.SourceGeographyID,
		arg.Year,
		arg.RawValue,
		arg.DisplayValue,
		arg.NumericValue,
		arg.LowerBound,
		arg.UpperBound,
		arg.ValueStatus,
		arg.PublishState,
		arg.SourceRowKey,
		arg.CanonicalM49Code,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ReleaseID,
		&i.SeriesID,
		&i.SourceGeographyID,
		&i.Year,
		&i.RawValue,
		&i.DisplayValue,
		&i.NumericValue,
		&i.LowerBound,
		&i.UpperBound,
		&i.ValueStatus,
		&i.PublishState,
		&i.SourceRowKey,
		&i.CanonicalM49Code,
		&i.CreatedAt,
	)
	return i, err
}

const insertSeries = `-- name: InsertSeries :one
INSERT INTO series (dataset_id, measure_code, label, dimensions, dimensions_hash, unit, statistic, value_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, dataset_id, measure_code, label, dimensions, dimensions_hash, unit, statistic, value_kind, created_at
`

type InsertSeriesParams struct {
	DatasetID      string `json:"dataset_id"`
	MeasureCode    string `json:"measure_code"`
	Label          string `json:"label"`
	Dimensions     []byte `json:"dimensions"`
	DimensionsHash string `json:"dimensions_hash"`
	Unit           string `json:"unit"`
	Statistic      string `json:"statistic"`
	ValueKind      string `json:"value_kind"`
}

func (q *Queries) InsertSeries(ctx context.Context, arg InsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, insertSeries,
		arg.DatasetID,
		arg.MeasureCode,
		arg.Label,
		arg.Dimensions,
		arg.DimensionsHash,
		arg.Unit,
		arg.Statistic,
		arg.ValueKind,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.MeasureCode,
		&i.Label,
		&i.Dimensions,
		&i.DimensionsHash,
		&i.Unit,
		&i.Statistic,
		&i.ValueKind,
		&i.CreatedAt,
	)
	return i, err
}

const insertSourceGeography = `-- name: InsertSourceGeography :one
WITH inserted AS (
    INSERT INTO source_geography (source_system, source_code, name, geography_kind, canonical_m49_code)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (source_system, source_code, geography_kind, name, canonical_m49_code) DO NOTHING
    RETURNING id, source_system, source_code, name, geography_kind, canonical_m49_code, created_at
)
SELECT id, source_system, source_code, name, geography_kind, canonical_m49_code, created_at FROM inserted
UNION ALL
SELECT id, source_system, source_code, name, geography_kind, canonical_m49_code, created_at
FROM source_geography
WHERE source_system = $1
  AND source_code = $2
  AND name = $3
  AND geography_kind = $4
  AND canonical_m49_code IS NOT DISTINCT FROM $5
LIMIT 1
`

type InsertSourceGeographyParams struct {
	SourceSystem     string      `json:"source_system"`
	SourceCode       string      `json:"source_code"`
	Name             string      `json:"name"`
	GeographyKind    string      `json:"geography_kind"`
	CanonicalM49Code pgtype.Text `json:"canonical_m49_code"`
}

type InsertSourceGeographyRow struct {
	ID               int64              `json:"id"`
	SourceSystem     string             `json:"source_system"`
	SourceCode       string             `json:"source_code"`
	Name             string             `json:"name"`
	GeographyKind    string             `json:"geography_kind"`
	CanonicalM49Code pgtype.Text        `json:"canonical_m49_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSourceGeography(ctx context.Context, arg InsertSourceGeographyParams) (InsertSourceGeographyRow, error) {
	row := q.db.QueryRow(ctx, insertSourceGeography,
		arg.SourceSystem,
		arg.SourceCode,
		arg.Name,
		arg.GeographyKind,
		arg.CanonicalM49Code,
	)
	var i InsertSourceGeographyRow
	err := row.Scan(
		&i.ID,
		&i.SourceSystem,
		&i.SourceCode,
		&i.Name,
		&i.GeographyKind,
		&i.CanonicalM49Code,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebSession = `-- name: InsertWebSession :one
INSERT INTO web_sessions (session_id, subject_id, token_hash, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING session_id, subject_id, token_hash, issued_at, expires_at
`

type InsertWebSessionParams struct {
	SessionID string             `json:"session_id"`
	SubjectID string             `json:"subject_id"`
	TokenHash []byte             `json:"token_hash"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertWebSession(ctx context.Context, arg InsertWebSessionParams) (WebSession, error) {
	row := q.db.QueryRow(ctx, insertWebSession,
		arg.SessionID,
		arg.SubjectID,
		arg.TokenHash,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i WebSession
	err := row.Scan(
		&i.SessionID,
		&i.SubjectID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAssociationPoints = `-- name: ListAssociationPoints :many
SELECT x.canonical_m49_code, x.numeric_value AS x_value, y.numeric_value AS y_value
FROM catalog_snapshot_release sx
JOIN observation x ON x.release_id = sx.release_id
JOIN catalog_snapshot_release sy ON sy.snapshot_id = sx.snapshot_id
JOIN observation y ON y.release_id = sy.release_id
WHERE sx.snapshot_id = $1
  AND x.series_id = $2
  AND x.year = $3
  AND y.series_id = $4
  AND y.year = $5
  AND x.value_status = 'numeric'
  AND y.value_status = 'numeric'
  AND x.publish_state = 'PUBLISHED'
  AND y.publish_state = 'PUBLISHED'
  AND x.canonical_m49_code IS NOT NULL
  AND x.canonical_m49_code = y.canonical_m49_code
  AND (coalesce(cardinality($6::text[]), 0) = 0 OR x.canonical_m49_code = ANY($6::text[]))
ORDER BY x.canonical_m49_code
`

type ListAssociationPointsParams struct {
	SnapshotID string   `json:"snapshot_id"`
	SeriesID   int64    `json:"series_id"`
	Year       int16    `json:"year"`
	SeriesID_2 int64    `json:"series_id_2"`
	Year_2     int16    `json:"year_2"`
	Column6    []string `json:"column_6"`
}

type ListAssociationPointsRow struct {
	CanonicalM49Code pgtype.Text    `json:"canonical_m49_code"`
	XValue           pgtype.Numeric `json:"x_value"`
	YValue           pgtype.Numeric `json:"y_value"`
}

func (q *Queries) ListAssociationPoints(ctx context.Context, arg ListAssociationPointsParams) ([]ListAssociationPointsRow, error) {
	rows, err := q.db.Query(ctx, listAssociationPoints,
		arg.SnapshotID,
		arg.SeriesID,
		arg.Year,
		arg.SeriesID_2,
		arg.Year_2,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssociationPointsRow{}
	for rows.Next() {
		var i ListAssociationPointsRow
		if err := rows.Scan(&i.CanonicalM49Code, &i.XValue, &i.YValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogDatasets = `-- name: ListCatalogDatasets :many
SELECT d.id AS dataset_id, d.who_indicator_id, d.who_measure_code, d.title,
       r.id AS release_id, r.accessed_at, r.source_url, r.citation
FROM catalog_snapshot_release csr
JOIN dataset d ON d.id = csr.dataset_id
JOIN dataset_release r ON r.id = csr.release_id
WHERE csr.snapshot_id = $1
ORDER BY d.title
`

type ListCatalogDatasetsRow struct {
	DatasetID      string             `json:"dataset_id"`
	WhoIndicatorID string             `json:"who_indicator_id"`
	WhoMeasureCode string             `json:"who_measure_code"`
	Title          string             `json:"title"`
	ReleaseID      int64              `json:"release_id"`
	AccessedAt     pgtype.Timestamptz `json:"accessed_at"`
	SourceUrl      string             `json:"source_url"`
	Citation       string             `json:"citation"`
}

func (q *Queries) ListCatalogDatasets(ctx context.Context, snapshotID string) ([]ListCatalogDatasetsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogDatasets, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogDatasetsRow{}
	for rows.Next() {
		var i ListCatalogDatasetsRow
		if err := rows.Scan(
			&i.DatasetID,
			&i.WhoIndicatorID,
			&i.WhoMeasureCode,
			&i.Title,
			&i.ReleaseID,
			&i.AccessedAt,
			&i.SourceUrl,
			&i.Citation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogSnapshotReleases = `-- name: ListCatalogSnapshotReleases :many
SELECT csr.snapshot_id, csr.dataset_id, csr.release_id, r.accessed_at, r.source_url, r.citation
FROM catalog_snapshot_release csr
JOIN dataset_release r ON r.id = csr.release_id
WHERE csr.snapshot_id = $1
ORDER BY csr.dataset_id
`

type ListCatalogSnapshotReleasesRow struct {
	SnapshotID string             `json:"snapshot_id"`
	DatasetID  string             `json:"dataset_id"`
	ReleaseID  int64              `json:"release_id"`
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
	SourceUrl  string             `json:"source_url"`
	Citation   string             `json:"citation"`
}

func (q *Queries) ListCatalogSnapshotReleases(ctx context.Context, snapshotID string) ([]ListCatalogSnapshotReleasesRow, error) {
	rows, err := q.db.Query(ctx, listCatalogSnapshotReleases, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogSnapshotReleasesRow{}
	for rows.Next() {
		var i ListCatalogSnapshotReleasesRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.DatasetID,
			&i.ReleaseID,
			&i.AccessedAt,
			&i.SourceUrl,
			&i.Citation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasetsWithRelease = `-- name: ListDatasetsWithRelease :many
SELECT DISTINCT dataset_id
FROM dataset_release
ORDER BY dataset_id
`

func (q *Queries) ListDatasetsWithRelease(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDatasetsWithRelease)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dataset_id string
		if err := rows.Scan(&dataset_id); err != nil {
			return nil, err
		}
		items = append(items, dataset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForM49Release = `-- name: ListGroupsForM49Release :many
SELECT g.m49_release_id, g.code, g.parent_code, g.name, g.group_kind, g.is_custom,
       m.geography_code
FROM m49_group g
LEFT JOIN m49_group_member m
    ON m.m49_release_id = g.m49_release_id AND m.group_code = g.code
WHERE g.m49_release_id = $1
ORDER BY g.group_kind, g.name, m.geography_code
`

type ListGroupsForM49ReleaseRow struct {
	M49ReleaseID  int64       `json:"m49_release_id"`
	Code          string      `json:"code"`
	ParentCode    pgtype.Text `json:"parent_code"`
	Name          string      `json:"name"`
	GroupKind     string      `json:"group_kind"`
	IsCustom      bool        `json:"is_custom"`
	GeographyCode pgtype.Text `json:"geography_code"`
}

func (q *Queries) ListGroupsForM49Release(ctx context.Context, m49ReleaseID int64) ([]ListGroupsForM49ReleaseRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForM49Release, m49ReleaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForM49ReleaseRow{}
	for rows.Next() {
		var i ListGroupsForM49ReleaseRow
		if err := rows.Scan(
			&i.M49ReleaseID,
			&i.Code,
			&i.ParentCode,
			&i.Name,
			&i.GroupKind,
			&i.IsCustom,
			&i.GeographyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsForSeries = `-- name: ListObservationsForSeries :many
SELECT o.id, o.dataset_id, o.release_id, o.series_id, o.source_geography_id, o.year, o.raw_value, o.display_value, o.numeric_value, o.lower_bound, o.upper_bound, o.value_status, o.publish_state, o.source_row_key, o.canonical_m49_code, o.created_at
FROM catalog_snapshot_release csr
JOIN observation o ON o.release_id = csr.release_id
WHERE csr.snapshot_id = $1
  AND o.series_id = $2
  AND o.year = ANY($3::smallint[])
ORDER BY o.year, o.source_geography_id
LIMIT $4 OFFSET $5
`

type ListObservationsForSeriesParams struct {
	SnapshotID string  `json:"snapshot_id"`
	SeriesID   int64   `json:"series_id"`
	Column3    []int16 `json:"column_3"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
}

func (q *Queries) ListObservationsForSeries(ctx context.Context, arg ListObservationsForSeriesParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsForSeries,
		arg.SnapshotID,
		arg.SeriesID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.ReleaseID,
			&i.SeriesID,
			&i.SourceGeographyID,
			&i.Year,
			&i.RawValue,
			&i.DisplayValue,
			&i.NumericValue,
			&i.LowerBound,
			&i.UpperBound,
			&i.ValueStatus,
			&i.PublishState,
			&i.SourceRowKey,
			&i.CanonicalM49Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseDatasetPairsByIDs = `-- name: ListReleaseDatasetPairsByIDs :many
SELECT id, dataset_id
FROM dataset_release
WHERE id = ANY($1::bigint[])
ORDER BY id
`

type ListReleaseDatasetPairsByIDsRow struct {
	ID        int64  `json:"id"`
	DatasetID string `json:"dataset_id"`
}

func (q *Queries) ListReleaseDatasetPairsByIDs(ctx context.Context, dollar_1 []int64) ([]ListReleaseDatasetPairsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listReleaseDatasetPairsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseDatasetPairsByIDsRow{}
	for rows.Next() {
		var i ListReleaseDatasetPairsByIDsRow
		if err := rows.Scan(&i.ID, &i.DatasetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesYearsForSnapshot = `-- name: ListSeriesYearsForSnapshot :many
SELECT DISTINCT o.year
FROM catalog_snapshot_release csr
JOIN observation o ON o.release_id = csr.release_id
WHERE csr.snapshot_id = $1 AND o.series_id = $2
ORDER BY o.year
`

type ListSeriesYearsForSnapshotParams struct {
	SnapshotID string `json:"snapshot_id"`
	SeriesID   int64  `json:"series_id"`
}

func (q *Queries) ListSeriesYearsForSnapshot(ctx context.Context, arg ListSeriesYearsForSnapshotParams) ([]int16, error) {
	rows, err := q.db.Query(ctx, listSeriesYearsForSnapshot, arg.SnapshotID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int16{}
	for rows.Next() {
		var year int16
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSourceGeographies = `-- name: SearchSourceGeographies :many
SELECT id, source_system, source_code, name, geography_kind, canonical_m49_code, created_at
FROM source_geography
WHERE $1 = '' OR name ILIKE '%' || $1 || '%' OR source_code ILIKE '%' || $1 || '%'
ORDER BY name, source_code
LIMIT $2
`

type SearchSourceGeographiesParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchSourceGeographies(ctx context.Context, arg SearchSourceGeographiesParams) ([]SourceGeography, error) {
	rows, err := q.db.Query(ctx, searchSourceGeographies, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceGeography{}
	for rows.Next() {
		var i SourceGeography
		if err := rows.Scan(
			&i.ID,
			&i.SourceSystem,
			&i.SourceCode,
			&i.Name,
			&i.GeographyKind,
			&i.CanonicalM49Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCatalogHead = `-- name: SetCatalogHead :exec
INSERT INTO catalog_head (singleton, snapshot_id)
VALUES (true, $1)
ON CONFLICT (singleton) DO UPDATE
SET snapshot_id = EXCLUDED.snapshot_id, updated_at = now()
`

func (q *Queries) SetCatalogHead(ctx context.Context, snapshotID string) error {
	_, err := q.db.Exec(ctx, setCatalogHead, snapshotID)
	return err
}

const updateImportJob = `-- name: UpdateImportJob :one
UPDATE import_job
SET release_id = $2,
    state = $3,
    discovered_url = $4,
    staged_raw_csv = $5,
    preview = $6,
    error_message = $7,
    started_at = $8,
    finished_at = $9
WHERE id = $1
RETURNING id, dataset_id, release_id, requested_by, import_kind, state, source_url, discovered_url, staged_raw_csv, preview, error_message, expires_at, created_at, started_at, finished_at
`

type UpdateImportJobParams struct {
	ID            int64              `json:"id"`
	ReleaseID     pgtype.Int8        `json:"release_id"`
	State         string             `json:"state"`
	DiscoveredUrl pgtype.Text        `json:"discovered_url"`
	StagedRawCsv  []byte             `json:"staged_raw_csv"`
	Preview       []byte             `json:"preview"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateImportJob(ctx context.Context, arg UpdateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJob,
		arg.ID,
		arg.ReleaseID,
		arg.State,
		arg.DiscoveredUrl,
		arg.StagedRawCsv,
		arg.Preview,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ReleaseID,
		&i.RequestedBy,
		&i.ImportKind,
		&i.State,
		&i.SourceUrl,
		&i.DiscoveredUrl,
		&i.StagedRawCsv,
		&i.Preview,
		&i.ErrorMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
